# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
