# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-19 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20180219_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
